### PR TITLE
Improve for Fix Server only if Fixer is true

### PR DESCRIPTION
**Pull request by SJang1**
For users only want to see server, does not want to fix it.

Haven't checked what happens if server changes while watching, but I think it will work properly.

### CODE REVIEW

**Comment by nomomo** [comment]
A variable named "FIXER" already works as "FixServer_STATUS".
And, channel change notifications work well now regardless of the 'Server fixer'.

See the videos below.
[https://www.twitch.tv/videos/496675356?t=01h13m30s](https://www.twitch.tv/videos/496675356?t=01h13m30s)
[https://www.twitch.tv/videos/496675356?t=01h29m30s](https://www.twitch.tv/videos/496675356?t=01h29m30s)
He is not using the 'Server fixer'.

'Server Fixer' is a feature to connect to a specific server that a user wants and is currently under development. This method can put a heavy load on the Twitch server when used by many users. So this feature is currently disabled and hidden from normal users.

The value of "FIXER" must be true for the 'Server fixer' to be used.
But the default value of "FIXER" is false and normal users cannot change this value.

**Comment by SJang1** [comment]
> The value of "FIXER" must be true for the 'Server fixer' to be used.
> But the default value of "FIXER" is false and normal users cannot change this value.

But as for me, with the default value, Fixer is setted to false but it tries, and does fixes the server.
This is why I wrote this, and this works.

Environment on Fedora 31, Firefox 70.0

**Comment by nomomo** [comment]
Any problem does not occur on Windows 10, Firefox 70.0.
Do you have the same problem after completely deleting the script and reinstalling the script?

**Comment by SJang1** [comment]
Same problem even after it.

**Comment by SJang1** [comment]
I now had tried to completely delete and reinstall few times, and now there seems no problem for it.

I am not sure if this is a script problem or user environment problem. Hmmm......

**Comment by nomomo** [comment]
The "FIXER" value is stored in Tampermonkey's storage. If you delete the script completely without overwriting it, this storage will be completely cleared.
Usually the storage is initialized with one delete and reinstallation, but I don't know why it was initialized after several deletions and reinstallations. Maybe it was cached.

So why did the Server Fixer feature work for you? Obviously, the default value of "FIXER" value is false, and if "FIXER" is false, the code in the block marked as "Server Fixer (Auto Reconnector)" cannot be executed.

Of course this could be an environmental issue as you said, but I think...
Perhaps "FIXER" value was saved as true while you reviewed and modified the code, or the "Server Fixer" feature was turned on through the following ways.
1. Type "TWITCH_SERVER_INFO_FIXER ()" in the console window.
2. You may have clicked the server display area seven times quickly, to copy the server name and url. Copying seven times can turn 'Server Fixer' feature on and off. This is an Easter egg.

**Comment by SJang1** [comment]
It was happening from when I had first-installed the script before, so this doesn't mean anything like something you said.

**Comment by nomomo** [comment]
I just inserted debug code into the script to check for this problem. You can run DEBUG MODE by typing "TWITCH_SERVER_INFO_DEBUG()" in the console window while the script is running. If the same problem occurs, please let me know the value of "FIXER" printed in the console window.

**Comment by SJang1** [comment]
This looks like it goes to issue, I'll close here, and open on issue when happening again.

**Pull request closed without merging**
